### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by msimet** [msimet/Stile#17]
We agreed in issue #1 to use sphinx for documentation; this issue is to remind us to set that up (at some point in the future when we have more functionality, probably).

**Comment by msimet** [comment]
Hey folks--I remember we made a decision about how to write defaults in the documentation, and it was either `(default: None)` or `[default: None]` but I don't remember which one we preferred.  Both are in use in the code, so I can't tell from that!  Anyone remember what we decided?

**Comment by HironaoMiyatake** [comment]
Hmmm, I do not remember... Sorry!

**Comment by rmandelb** [comment]
I don�t either.  I recommend just picking something and fixing it directly on master.

**Comment by msimet** [comment]
FYI @HironaoMiyatake (and anyone else with open branches)--I just committed a bunch of whitespace edits to master along with the `[default]` convention.  I've merged it with all open branches, but you'll want to pull before editing anything.
