### ISSUE TITLE
priorities for January

### ISSUE THREAD

**Issue by rmandelb** [msimet/Stile#51]
This is an issue for collecting priorities for Stile work in January.

@msimet , you mentioned some priorities to me, verbally.  @HironaoMiyatake , do you have any thoughts?  Are there any important things for which we don't have a person to work on it?

**Comment by rmandelb** [comment]
Hi Melanie - something related to this came up at the HSC software meeting at Princeton today (which I called into). If we want to do star-galaxy correlations, am I right that your work on #45 has to happen?  How much work is this / what is an estimated timeline for that work?  Aside from #45, does anything else need to be completed in order to enable meaningful star-galaxy correlations?

**Comment by msimet** [comment]
#45 is necessary for star-galaxy correlations involving shape, yes, and I think that's it.  

If all you wanted was position, on the other hand, then we'd need to write a module to make randoms, and I think that's more suited for some of the restructuring on...hmm, I don't really have an issue for that, but the restructuring where we call the (say) CCD-level tests as we're gathering the data for the visit-level tests.  But I assume you're talking about correlations involving shapes?

I can try to work on it this week at AAS but I'll also have some other demands on my time (and will spend most of Fri in transit)--I will plan on having some usable code for this early next week.

**Comment by rmandelb** [comment]
Yes, this is for correlations of shape, not position.

That timeline sounds good.
