### ISSUE TITLE
detect.is-primary for HSC patch-level tests?

### ISSUE THREAD

**Issue by msimet** [msimet/Stile#52]
First of all, a note that I just pushed commit https://github.com/msimet/Stile/commit/c2131a2b34488bd1213c9c57fd2741b9a8f7e412 which is a bugfix for the case where we're trying to mask on `detect.is-primary`.  (The previous implementation didn't work if the catalog had already been masked by other flags.)

Second, right now, we mask on `detect.is-primary` for both the patch and tract-level tests.  My question is whether we want to do that for the patch-level test.  Tract we need it to avoid duplication; on the patch level, do we want to be checking the performance for things that were analyzed in the patch, but won't be used for our final analysis?

**Comment by HironaoMiyatake** [comment]
I think we might want to use `detect.is-primary` also on the patch level. We might not want to avoid duplicates even if they are in different patches... But it's not a strong opinion..

**Comment by rmandelb** [comment]
@TallJimbo , I know you haven't been following Stile development rather closely but since this question relates to flags from the HSC pipeline, i was wondering if you have any comments?

**Comment by TallJimbo** [comment]
I don't think I have any special insight here.  In any analysis that covers multiple patches, you definitely do want to use that flag, but for anything that's confined to one patch it's just a matter of preference - do you want to get more information on the edges, or be more consistent with multi-patch analyses?

**Comment by rmandelb** [comment]
Okay.  In that case I would go with requiring ```detect.is_primary``` even when analyzing a single patch, since those are the objects that will get used if we were to later go to the analysis of a larger area.

**Comment by msimet** [comment]
Well, that's two votes for keeping the flag. I'll close this issue this
evening unless anyone objects before then!

**Comment by msimet** [comment]
Well, slightly more than three months after I said I was going to close this...I'm closing it!
