### ISSUE TITLE
HSC module: multiple tract/visit runs

### ISSUE THREAD

**Issue by msimet** [msimet/Stile#60]
@HironaoMiyatake requested a way to analyze multiple visits or tracts at once (currently we only do one at a time).

**Comment by HironaoMiyatake** [comment]
What is the status of this issue? Now we have a bunch of tracts on several fields, so having this functionality is quite helpful!!

**Comment by msimet** [comment]
I have some stuff and was testing it, and then had a deadline I had to meet--will try to finish it today or this weekend.

**Comment by HironaoMiyatake** [comment]
Thanks!
