### ISSUE TITLE
Correlation functions of star and PSF sizes

### ISSUE THREAD

**Issue by msimet** [msimet/Stile#67]
We do correlation functions of shapes already, but sizes would also be good.  This should be very simple, but I thought I'd give it its own issue.

**Comment by rmandelb** [comment]
Presumably this should be the correlation function of normalized residual size?  i.e., the correlation function of something like

(sigma PSF - sigma star) / (sigma star)?

**Comment by msimet** [comment]
Ah, good point, thanks.
