### ISSUE TITLE
Publishing documentation

### ISSUE THREAD

**Issue by msimet** [msimet/Stile#99]
It would be nice to be able to link to the documentation. (There's currently a space in the HSC shear catalog paper for this.)  I think the easiest option is probably [ReadTheDocs](https://docs.readthedocs.io/en/latest/index.html), which we can set up to rebuild every time we commit something to master, and which would support versioning if we ever get there.  Does that sound okay to everyone?  Anyone have better ideas? @HironaoMiyatake @rmandelb pinging you in particular.

If there are no objections, I can go ahead and set it up.

**Comment by rmandelb** [comment]
I like ReadTheDocs.  Go for it.

**Comment by msimet** [comment]
Woohoo! http://stile.readthedocs.io/ (I'll go add this to the readme, too.)
